services:
  postgres:
      container_name: postgres_db
      image: postgres
      restart: always
      ports:
          - "${DB_PORT}:${DB_PORT}"
      environment:
          POSTGRES_PASSWORD: 1q2w3e4r
          POSTGRES_USER: postgres